package model;

public enum Endpoint {
    GET_TASKS,
    GET_TASK,
    GET_EPIC,
    GET_SUB,
    GET_TASKID,
    GET_EPICID,
    GET_SUBID,
    GET_ALLSUBEPIC,
    GET_HISTORY,
    POST_TASK,
    POST_EPIC,
    POST_SUB,
    POST_UPDATETASK,
    POST_UPDATEEPIC,
    POST_UPDATESUB,
    DELETE_TASK,
    DELETE_EPIC,
    DELETE_SUB,
    DELETE_TASKID,
    DELETE_EPICID,
    DELETE_SUBID,
    UNKNOW
}
